### PR TITLE
Restore removeDuplicates and Fix observing stale state

### LINKED ISSUE #57: Pull to refresh behavior issues
Hello, first of all, thank you for creating this amazing open-source project.

I encountered a bug with pull to refresh after updating to version 0.6.0. 

In some cases, there are states in the store, like token or since, that are unrelated to the view. However, it seems that with the recent commit (https://github.com/johnpatrickmorgan/TCACoordinators/commit/865ef58e8f0ee4dc70c28b22174ffac7adf02e23), when the state changes, the Router also updates simultaneously, causing the pull to refresh not to work.

So I was wondering if I could open a PR on TCARouter to allow for setting viewStore isDuplicated closures in the initializer. ( I think that would also allow for optimizations for route updates. ) 

------------------------------------------------------------------------------------------------------------------------

https://github.com/johnpatrickmorgan/TCACoordinators/assets/25315898/fa77de83-2881-4242-a234-b20802e7da9d

[TCACoordinatorPullToRefresh.zip](https://github.com/johnpatrickmorgan/TCACoordinators/files/12711218/TCACoordinatorPullToRefresh.zip)

```swift
struct LogInView: View {
  struct ViewState: Equatable {
    let items: IdentifiedArrayOf<Item>
    
    init(state: LogIn.State) {
      self.items = state.items
    }
  }
  // ...
  
  var body: some View {
    WithViewStore(self.store, observe: ViewState.init) { viewState in
        //...
      }
      .refreshable {
        await self.store.send(.pullToRefresh).finish()
      }
    }
  }
}

struct LogIn: Reducer {
  struct State: Equatable {
    let id = UUID()
    var since: String? = "since"
    var items: IdentifiedArrayOf<Item> = [Item()]
  }

  enum Action {
    case pullToRefresh
    case itemLoaded(items: [Item])
  }

  var body: some ReducerOf<Self> {
    Reduce { state, action in
      switch action {
      // The first action always fail, and subsequent actions will succeed.
      case .pullToRefresh:
        state.since = nil
        
        return .run { [since = state.since] send in
          await send(.itemLoaded(items: self.loadItem(since: since)))
        }
        
      case .itemLoaded(let items):
        state.items = .init(uniqueElements: items)
        return .none
      }
    }
  }
  
  func loadItem(since: String?) async -> [Item] {
    try? await Task.sleep(for: .seconds(2))
    var items: [Item] = []
    
    for _ in 0..<20 {
      items.append(Item())
    }
    
    return items
  }
}
```

### PR DESCRIPTION
**Pull request by heoblitz**
Restoring removeDuplicates to address performance improvements and resolve side-effect bugs, and making changes to ensure that the TCA router's viewStore always receives the up-to-date values.

close #57

### CODE REVIEW

File: Sources/TCACoordinators/TCARouter/TCARouter.swift [hunk 1]
```diff
@@ -34,16 +34,16 @@ public struct TCARouter<
       }
     )
   }
-
+  
   public var body: some View {
     Router(
-      viewStore.binding(get: routes, send: updateRoutes),
+      viewStore.binding(get: { _ in store.withState(routes) }, send: updateRoutes),
```
Comment (johnpatrickmorgan) [inline Sources/TCACoordinators/TCARouter/TCARouter.swift:40]: In my testing, this still had stale data, but the following always had the latest data:
```suggestion
      ViewStore(store, observe: { $0 }).binding(get: routes, send: updateRoutes),
```

**Comment by johnpatrickmorgan** [comment]
Thanks so much @heoblitz - I confirmed that restoring `removeDuplicates` fixes the bugs you raised. I still saw stale data issues after your fix (I'll add a test case soon), but found that the following ensured the binding always has access to the latest state:

```swift
ViewStore(store, observe: { $0 }).binding(get: routes, send: updateRoutes),
```

Thanks for all your help!

**Comment by heoblitz** [comment]
Thank you so much for the quick release :)
